### ISSUE TITLE
Arreglar NavBar

### ISSUE THREAD

**Issue by JEdilbertoTC** [JEdilbertoTC/del-parque#50]
El navbar debe verse bien tanto en computadora, laptop, tablet y celular

**Comment by GabrielVillagran** [comment]
tambien ando checando esto

**Comment by GabrielVillagran** [comment]
De momento quedo asi 
![image](https://user-images.githubusercontent.com/44887537/185834267-e07f79ff-13cd-42ee-9798-c2d556b00159.png)
**La idea es modificar el menú para la entrega final y que este quede más presentable y ordenado**

**Comment by GabrielVillagran** [comment]
Se arregló la barra de navegación agregando una más estética y presentable
