### ISSUE TITLE
Hacer responsive todas las paginas

### ISSUE THREAD

**Issue by JEdilbertoTC** [JEdilbertoTC/del-parque#51]
Todas las paginas deben poder verse bien sin necesidad de hacer zoom

**Comment by LuisFragaFM** [comment]
Se hizo la pagina de registro de paquetes responsiva y falta modificar el sobrante de la pagina

**Comment by LuisFragaFM** [comment]
se modifico el encabezado ya que a los 400 px de pantalla (anchura) se rompia el usuario

**Comment by LuisFragaFM** [comment]
se modifico las pantallas de los trajadores ya son responsivas pero falta la funcionabilidad de los botones
